version: '2'

networks:
  monitoring-network:
    driver: bridge

services:
    cassandra:
      build: ./cassendra
      container_name: cassandra
      ports:
      - "9042:9042"
      depends_on:
      - influxdb
    influxdb:
      image: influxdb:0.13.0 
      environment:
        - INFLUXDB_GRAPHITE_ENABLED=true
      ports:
        - "8083:8083"
        - "8086:8086"
      volumes:
        - ./var/lib/influxdb/data:/var/lib/influxdb/data
        - ./etc/influxdb:/etc/influxdb
    grafana:
      image: grafana/grafana:4.3.2
      container_name: grafana
      ports:
      - "9000:3000"
      volumes:
        - ./var/lib/grafana/plugins:/var/lib/grafana/plugins
      depends_on:
      - influxdb
   